# Generated by Django 5.0.3 on 2024-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contact_number',
            field=models.IntegerField(default=0),
        ),
    ]
